# Generated by Django 5.2.6 on 2025-09-19 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('address', models.CharField(max_length=500)),
                ('open_time', models.CharField(help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bar', 'Bar'), ('hotel', 'Hotel'), ('shop', 'Shop'), ('service', 'Service'), ('attraction', 'Attraction'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.JSONField(default=list, help_text="List of tags, e.g., ['Grill', 'Family', 'Outdoor']")),
                ('image', models.URLField(help_text='URL to the listing image', max_length=1000)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
